[package]
name = "numerical-sofa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
geo = "0.26.0"
optimization = "0.2.0"
